### ISSUE TITLE
when i am running run_class_finetune_FedAvg.py getting below error

### ISSUE THREAD

**Issue by chillum1718** [rui-yan/SSL-FL#14]
command:
python run_class_finetune_FedAvg.py --finetune /workspace/nvidia/pradeep/SSL-FL/output/covidfl_pretrain_beit_base_central_checkpoint-999.pth --output_dir /workspace/nvidia/pradeep/SSL-FL/OUTPUT_PATH_FT/ --save_ckpt --num_workers 1 --log_dir /home/SSL-FL/log_dir/ --nb_classes 3 --n_clients 5 --num_local_clients -1

value:  0.9479166865348816
avg:  0.9441117986947477
best_acc: 0.9402445297755168
current_acc: 0.9441117986947477
Calculate the model avg----
Update each client model parameters----
++++++ Running Validation ++++++
Traceback (most recent call last):
  File "run_class_finetune_FedAvg.py", line 500, in <module>
    main(args, model)
  File "run_class_finetune_FedAvg.py", line 446, in main
    test_stats = valid(args, model_avg, data_loader_val)
  File "/workspace/nvidia/pradeep/SSL-FL/code/util/FedAvg_utils.py", line 366, in valid
    for batch in metric_logger.log_every(data_loader, 10, header):
  File "/workspace/nvidia/pradeep/SSL-FL/code/util/misc.py", line 176, in log_every
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 224, 224] at entry 0 and [3, 224, 360] at entry 5

**Comment by chillum1718** [comment]
solved
